/**
 * Movinsafe API
 * Movinsafe API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Position } from './position';
import { Alert } from './alert';


export interface Device { 
    name?: string;
    uniqueId?: string;
    protocol?: string;
    workspaceId?: string;
    expirationTime?: string;
    status?: string;
    positions?: Array<Position>;
    alerts?: Array<Alert>;
    contact?: string;
    model?: string;
    phone?: string;
    attributes?: { [key: string]: object; };
    geofenceIds?: Array<number>;
    groupId?: number;
    disabled?: boolean;
    category?: string;
    lastUpdate?: string;
}

