/**
 * Movinsafe API
 * Movinsafe API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Position { 
    deviceUID?: number;
    protocol?: string;
    deviceTime?: string;
    fixTime?: string;
    serverTime?: string;
    outdated?: boolean;
    valid?: boolean;
    latitude?: number;
    longitude?: number;
    date?: string;
    altitude?: number;
    battery?: number;
    speed?: number;
    course?: number;
    address?: string;
    accuracy?: number;
    attributes?: { [key: string]: object; };
}

