/**
 * Movinsafe API
 * Movinsafe API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserRestrictedDTO { 
    id?: string;
    firstName?: string;
    lastName?: string;
    email?: string;
    role?: UserRestrictedDTO.RoleEnum;
}
export namespace UserRestrictedDTO {
    export type RoleEnum = 'manager' | 'member';
    export const RoleEnum = {
        Manager: 'manager' as RoleEnum,
        Member: 'member' as RoleEnum
    };
}


