/**
 * Movinsafe API
 * Movinsafe API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ConfigurationDTO } from './configurationDTO';
import { Organisation } from './organisation';
import { Device } from './device';


export interface Workspace { 
    configuration?: Array<ConfigurationDTO>;
    id?: string;
    name?: string;
    organisation?: Organisation;
    workspaces?: Array<Workspace>;
    devices?: Array<Device>;
}

